[general]
taskrc = "~/.config/task/taskrc"
targets = ["ado_issues_omr", "ado_issues_rxp", "ado_issues_infra", "ado_issues_other"]
static_fields = ["project", "priority"]
annotation_comments = false
annotation_links = false

[ado_issues_omr]
service = "azuredevops"
description_template = "{{adotitle}}"
PAT="@oracle:eval:echo $AZURE_DEVOPS_PAT"
project = "VIS - Program 0"
organization = "ZEISSgroup-VIS"
wiql_filter = "[System.AssignedTo] = @me AND [System.State] <> 'Closed' AND [System.State] <> 'Removed' AND [System.AreaPath] = 'VIS - Program 0\\OM LOG'"
project_template = "OMR"
add_tags = ["ado"]

[ado_issues_rxp]
service = "azuredevops"
description_template = "{{adotitle}}"
PAT="@oracle:eval:echo $AZURE_DEVOPS_PAT"
project = "VIS - Program 0"
organization = "ZEISSgroup-VIS"
wiql_filter = "[System.AssignedTo] = @me AND [System.State] <> 'Closed' AND [System.State] <> 'Removed' AND [System.AreaPath] = 'VIS - Program 0\\Rx Recognition App'"
project_template = "RXP"
add_tags = ["ado"]

[ado_issues_infra]
service = "azuredevops"
description_template = "{{adotitle}}"
PAT="@oracle:eval:echo $AZURE_DEVOPS_PAT"
project = "VIS - Program 0"
organization = "ZEISSgroup-VIS"
wiql_filter = "[System.AssignedTo] = @me AND [System.State] <> 'Closed' AND [System.State] <> 'Removed' AND [System.AreaPath] = 'VIS - Program 0\\P0 Platform and Infrastructure'"
project_template = "Infra"
add_tags = ["ado"]

[ado_issues_other]
service = "azuredevops"
description_template = "{{adotitle}}"
PAT="@oracle:eval:echo $AZURE_DEVOPS_PAT"
project = "VIS - Program 0"
organization = "ZEISSgroup-VIS"
wiql_filter = "[System.AssignedTo] = @me AND [System.State] <> 'Closed' AND [System.State] <> 'Removed' AND [System.AreaPath] <> 'VIS - Program 0\\OM LOG' AND [System.AreaPath] <> 'VIS - Program 0\\P0 Platform and Infrastructure' AND [System.AreaPath] <> 'VIS - Program 0\\P0 Platform and Infrastructure'"
project_template = ""
add_tags = ["ado"]

[notifications]
notifications = true
backend = "applescript"
only_on_new_tasks = true
