git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never -n -s --color-only
os:
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote-tab {{filename}})'
